# Generated by Django 4.0.2 on 2022-02-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='name',
            field=models.JSONField(),
        ),
    ]
