# Generated by Django 4.0.2 on 2022-02-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_orderlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
