# Generated by Django 4.0.2 on 2022-02-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_orderlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='customer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
