# Generated by Django 4.0.2 on 2022-02-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_orderlist_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='completed',
            field=models.BooleanField(null=True),
        ),
    ]
