# Generated by Django 4.0.2 on 2022-02-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_rename_completed_orderlist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
    ]
