# Generated by Django 4.0.2 on 2022-02-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_orderlist_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='key',
        ),
    ]
